<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UserSecretsId>SiFutbolNoCF-6b63ca0c-c603-4951-b0db-64dfd60e7e17</UserSecretsId>
    <StartupObject>ManageDns.Program</StartupObject>
    <AssemblyTitle>SiFutbolNoCF</AssemblyTitle>
    <ApplicationIcon>imgs\SiFutbolNoCF.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="build\**" />
    <EmbeddedResource Remove="build\**" />
    <None Remove="build\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="imgs\SiFutbolNoCF.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.local.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
